config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#about'
  
  resources :goals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  validates :title,
            presence: true,
            length: { maximum: 80 }

  validates :description,
            presence: true,
            length: { maximum: 500 }
    
  validates :due_date,
            presence: true

  validate :due_date_cannot_be_in_the_past, :due_date_year_cannot_be_more_than_allowable, if: :due_date_changed?
  scope :completed, -> { where(complete: true) }
  scope :incomplete, -> { where(complete: false) }
  enum priority: { low: 0, medium: 1, high: 2 }

  private

  def due_date_cannot_be_in_the_past
    if due_date.present? && due_date < Time.zone.today
      errors.add(:due_date, 'cannot be earlier than today')
    end
  end

  def due_date_year_cannot_be_more_than_allowable
    if due_date.present? && due_date.to_date.year > 2100
      errors.add(:due_date, "a year cannot be more than 2100")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @goals = filtered_goals
    @goals.order('complete, due_date, priority DESC, title')
  end

  def show
    @goal = Goal.find_by(id: params[:id])
  end

  def new
    @goal = Goal.new
  end

  def edit
    @goal = Goal.find_by(id: params[:id])
  end

  def update
    @goal = Goal.find_by(id: params[:id])
    if @goal.update_attributes(goal_params)
      flash[:success] = 'Your goal has been successfully updated'
      if @goal.complete?
        redirect_to goals_path(filter: 'completed')
      else
        redirect_to goals_path
      end
    else
      flash.now[:error] = 'Please fill in all necessary fields.'
      render 'edit'
    end
  end

  def destroy
    @goal = Goal.find_by(id: params[:id])
    @goal.destroy
    flash[:info] = 'Your goal has been successfully deleted'
    redirect_to goals_path
  end

  def create
    @goal = Goal.new(goal_params)
    if @goal.save
      flash[:success] = 'Your goal has been successfully created'
      redirect_to goals_path
    else
      flash.now[:error] = 'Please fill in all necessary fields.'
      render 'new'
    end
  end

  def goal_params
    params.require(:goal).permit(:title, :description, :priority, :due_date, :complete)
  end

  def filtered_goals
    if params[:filter] == 'completed'
      Goal.completed
    elsif params[:filter] == 'incomplete'
      Goal.incomplete
    else
      Goal.all
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/goals/edit.html.erb
<!-- This page ha sthe same HTML as 'Create goal' page. The only difference is title name -->
<div class="goals-page">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <h1 class="goals-page__title">Edit Goal</h1>

        <div class="create-goal__card main-card">
          <%= simple_form_for @goal, defaults: { label_html: { class: 'main-input__label' } } do |f| %>
              <%= f.input :title, input_html: { class: 'main-input__field' }, wrapper_html: { class: 'main-input' }, required: false %>
              <%= f.input :description, input_html: { class: 'main-input__field main-input__field--textarea', rows: 4 }, wrapper_html: { class: 'main-input' }, required: false %>
              <%= f.input :priority, selected: [ ['Low', 'low'] ], collection: [['Low', 'low'], ['Medium', 'medium'], ['High', 'high']], input_html: { class: 'main-input__field main-input__field--xs' }, wrapper_html: { class: 'create-goal__input-short  main-input' }  %>
              <%= f.input :due_date, as: :string, input_html: { class: 'main-input__field main-input__field--xs', type: 'date' }, wrapper_html: { class: 'create-goal__input-short  main-input' }, required: false %>
              <div class="create-goal__form-footer">
              <%= link_to goals_path do %>
                  <button type="button" class="main-btn main-btn--xs main-btn--grey mr-16">Cancel</button>
              <% end %>
              <%= f.button :submit, class: 'main-btn main-btn--xs main-btn--submit' %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/goals/index.html.erb
<div class="goals-page">
  <div class="goals-page__container container">

    <% if Goal.exists? %>
      <% flash.each do |type, message| %>
        <div class="main-alert main-alert--<%= type %>">
          <i class="main-alert__icon icon icon-circle-check-bold"></i>
          <p class="main-alert__txt">
            <%= message %>
          </p>
        </div>
      <% end %>

      <div class="goals-page__header">
        <h1 class="goals-page__title">My Goals</h1>
        <%= link_to 'Create a Goal', new_goal_path,  class: "main-btn main-btn--xs mb-20 d-md-none" %>
      </div>

      <div class="goals-page__nav main-card">
        <div class="main-tab">
          <%= link_to "All #{Goal.count}", goals_path,  class: "main-tab__item #{'main-tab__item--active' if params[:filter].blank?}" %>
          <%= link_to "Incomplete #{Goal.incomplete.count}", goals_path(filter: 'incomplete'),  class: "main-tab__item #{'main-tab__item--active' if params[:filter] == 'incomplete'}" %>
          <%= link_to "Completed #{Goal.completed.count}", goals_path(filter: 'completed'),  class: "main-tab__item #{'main-tab__item--active' if params[:filter] == 'completed'} " %>
        </div>
        <div class="d-none d-md-block">
          <%= link_to 'Create a Goal', new_goal_path,  class: "main-btn main-btn--xs" %>
        </div>
      </div>

      <div class="goals-page__card main-card">
        <div class="overflow-x-auto">
          <table class="goals-page__table main-table">
            <thead>
              <tr>
                <th>Goal Name</th>
                <th width="160">Due Date</th>
                <th width="160">Priority</th>
              </tr>
            </thead>
            <tbody>
              <% @goals.each do |goal| %>
                <% if goal.complete?%>
                  <tr class="main-table__row--checked">
                <% else %>
                  <tr>
                <% end %>
                    <td>
                      <div class="d-flex align-items-center">
                        <% if goal.complete?%>
                          <i class="main-table__check main-table__check--active icon icon-circle-check-filled"></i>
                        <% else %>
                          <i class="main-table__check icon icon-circle-check"></i>
                        <% end %>
                        <%= link_to goal.title, goal_path(goal) %>
                      </div>
                    </td>
                    <td>
                      <%= goal.due_date %>
                    </td>
                    <td>
                      <div class="d-flex align-items-center">
                        <% if goal.low? %>
                          <i class="in-low mr-4 icon icon-arrow-down"></i>
                        <% elsif goal.medium? %>
                          <i class="in-medium mr-4 icon icon-arrow-up"></i>
                        <% else %>
                          <i class="in-high mr-4 icon icon-arrow-up"></i>
                        <% end %>
                        <%= goal.priority.capitalize %>
                      </div>
                    </td>
                  </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

    <% else %>

      <h1 class="goals-page__title">My Goals</h1>

      <div class="empty-goals__card main-card">
        <%=image_tag('working.svg', alt: 'Process', class: 'empty-goals__img')%>

        <p class="empty-goals__descr">You have no goals. Not going to lie, this is a bit sad.</p>

        <%= link_to 'Create a Goal', new_goal_path,  class: "main-btn"%>
      </div>

    <% end %>
  </div>
</div>

app/views/goals/new.html.erb
<!-- This page has the same HTML as 'Edit goal' page. The only difference is title name -->
<div class="goals-page">
<% if flash[:error].present? %>
  <div class="main-alert main-alert--error">
    <i class="main-alert__icon icon icon-triangle-warning"></i>
    <p class="main-alert__txt">
      <%= flash[:error] %>
    </p>
  </div>
<% end %>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-3">
        <h1 class="goals-page__title">Create a Goal</h1>

        <div class="create-goal__card main-card">
          <%= simple_form_for @goal, defaults: { label_html: { class: 'main-input__label' } } do |f| %>
            <%= f.input :title, input_html: { class: 'main-input__field' }, wrapper_html: { class: 'main-input' }, required: false %>
            <%= f.input :description, input_html: { class: 'main-input__field main-input__field--textarea', rows: 4 }, wrapper_html: { class: 'main-input' }, required: false %>
            <%= f.input :priority, selected: [ ['Low', 'low'] ], collection: [['Low', 'low'], ['Medium', 'medium'], ['High', 'high']], input_html: { class: 'main-input__field main-input__field--xs' }, wrapper_html: { class: 'create-goal__input-short  main-input' }  %>
            <%= f.input :due_date, as: :string, input_html: { class: 'main-input__field main-input__field--xs', type: 'date' }, wrapper_html: { class: 'create-goal__input-short  main-input' }, required: false %>
            <div class="create-goal__form-footer">
              <%= link_to goals_path do %>
                <button type="button" class="main-btn main-btn--xs main-btn--grey mr-16">Cancel</button>
              <% end %>
              <%= f.button :submit, class: 'main-btn main-btn--xs main-btn--submit' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/goals/show.html.erb
<div class="view-goal goals-page">
  <div class="view-goal-nav">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 offset-lg-2">
          <%= link_to goals_path, { class: "icon-btn icon-btn--blue" }  do %>
            <i class="icon-btn__icon icon icon-angle-left"></i>
            <span class="icon-btn__txt">My Goals</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <div class="main-card">
          <div class="view-goal-card__header">
            <% if @goal.complete? %>
              <button type="button" class="main-btn main-btn--green main-btn--xxs">
                <i class="main-btn__icon icon icon-check"></i>
                Completed
              </button>
              <% else %>
                <%= link_to goal_path(@goal, goal: { complete: true }), class: 'main-btn main-btn--grey-border main-btn--xxs', method: :put do %>
                  <i class="main-btn__icon icon icon-check"></i>
                  Mark Complete
                <% end %>
              <% end %>
              <div class="d-flex align-items-center">
                <%= link_to edit_goal_path(@goal), class: 'icon-btn mr-16' do %>
                  <i class="icon-btn__icon icon icon-edit mr-4"></i>
                  <span class="icon-btn__txt d-none d-md-inline-block">Edit</span>
                <% end %>
                <%= link_to goal_path(@goal), class: 'icon-btn', method: :delete, data: { confirm: "Are you sure you want to delete this goal?" } do %>
                  <i class="icon-btn__icon icon icon-bin mr-4"></i>
                  <span class="icon-btn__txt d-none d-md-inline-block">Delete</span>
                <% end %>
            </div>
          </div>

          <div class="view-goal-card__body">
            <div class="view-goal-card__subheader">
              <h1 class="view-goal-card__title">
                <%= @goal.title %>
              </h1>
              <div class="d-md-flex">
                <div class="view-goal-card__details">
                  <div class="view-goal-card__details-label">
                    <i class="icon icon-calendar mr-8"></i>
                    Due Date
                  </div>
                  <%= @goal.due_date.strftime('%d.%m.%y') %>
                </div>
                <div class="view-goal-card__details">
                  <div class="view-goal-card__details-label">
                    Priotity:
                  </div>
                  <% if @goal.low? %>
                    <i class="in-low icon icon-arrow-down"></i>
                  <% elsif @goal.medium? %>
                    <i class="in-medium icon icon-arrow-up"></i>
                  <% else %>
                    <i class="in-high icon icon-arrow-up"></i>
                  <% end %>
                  <%= @goal.priority.capitalize %>
                </div>
              </div>
            </div>

            <div class="view-goal-card__descr">
              <p class="view-goal-card__descr-label">Description</p>
              <p>
                <%= @goal.description %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGirlsWorkshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="main-wrap">
    <header class="main-header">
      <%= link_to root_path, { class: "main-header__logo" }  do %>
        <%=image_tag('logo.svg', alt: 'BeFocused')%>
      <% end %>
      <%= link_to root_path, { class: "icon-btn" }  do %>
        <i class="icon-btn__icon icon icon-circle-info"></i>
        <span class="icon-btn__txt">About</span>
      <% end %>
    </header>

    <main class="main-content">
      <%= yield %>
    </main>
  </div>
</html>

app/views/layouts/stubs.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGirlsWorkshop</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main-wrap">
      <header class="main-header">
        <a href="/" class="main-header__logo">
          <%=image_tag('logo.svg', alt: 'BeFocused')%>
        </a>
        <a href="/" class="icon-btn">
          <i class="icon-btn__icon icon icon-circle-info"></i>
          <span class="icon-btn__txt">About</span>
        </a>
      </header>

      <main class="main-content">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="info-page">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <h1 class="info-page__title">Self-development goals tracker</h1>
        <h2 class="info-page__subtitle">
          BeFocused is a convenient centralized personal space for any students, learners or other interested in self-education and self-development people.
        </h2>
        <div class="info-page__descr">
          <p>Moreover, setting goals in the right way can help you achieve them! Each goal should be <strong>SMART</strong>, and here’s what it means:</p>
          <p><strong>Specific:</strong> Well defined, clear, and unambiguous</p>
          <p><strong>Measurable:</strong> With specific criteria that measure your progress towards the accomplishment of the goal</p>
          <p><strong>Achievable:</strong> Attainable and not impossible to achieve</p>
          <p><strong>Realistic:</strong> Within reach, realistic, and relevant to your life purpose</p>
          <p><strong>Timely:</strong> With a clearly defined timeline, including a starting date and a target date. The purpose is to create urgency.</p>
        </div>
        <%= link_to 'Get Started', goals_path,  class: "main-btn" %>
      </div>
      <div class="col-lg-5 offset-lg-1 d-none d-lg-block">
        <%=image_tag('process_1440.svg', alt: 'Process', class: 'info-page__img')%>
      </div>
    </div>
  </div>
</div>

app/views/stubs/home/about_page.html.erb
<!-- This page the same as home page the only difference is button name -->
<div class="info-page">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <h1 class="info-page__title">Self-development goals tracker</h1>
        <h2 class="info-page__subtitle">
          BeFocused is a convenient centralized personal space for any students, learners or other interested in self-education and self-development people.
        </h2>
        <div class="info-page__descr">
          <p>Moreover, setting goals in the right way can help you achieve them! Each goal should be <strong>SMART</strong>, and here’s what it means:</p>
          <p><strong>Specific:</strong> Well defined, clear, and unambiguous</p>
          <p><strong>Measurable:</strong> With specific criteria that measure your progress towards the accomplishment of the goal</p>
          <p><strong>Achievable:</strong> Attainable and not impossible to achieve</p>
          <p><strong>Realistic:</strong> Within reach, realistic, and relevant to your life purpose</p>
          <p><strong>Timely:</strong> With a clearly defined timeline, including a starting date and a target date. The purpose is to create urgency.</p>
        </div>
        <button type="button" class="main-btn">Back to Goals</button>
      </div>
      <div class="col-lg-5 offset-lg-1 d-none d-lg-block">
        <%=image_tag('process_1440.svg', alt: 'Process', class: 'info-page__img')%>
      </div>
    </div>
  </div>
</div>

app/views/stubs/home/create_gaol_page.html.erb
<!-- This page has the same HTML as 'Edit goal' page. The only difference is title name -->
<div class="goals-page">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <h1 class="goals-page__title">Create a Goal</h1>

        <div class="create-goal__card main-card">
          <form>
            <!-- To show error style add main-input--error to main-input -->
            <div class="main-input main-input--error">
              <label class="main-input__label" for="goal_title">Goal Title</label>
              <input class="main-input__field" type="text" id="goal_title" />
              <div class="main-input__message">
                <i class="main-input__message-icon icon icon-triangle-warning-sm"></i>
                <span class="main-input__message-txt">Error message</span>
              </div>
            </div>

            <div class="main-input">
              <label class="main-input__label" for="goal_descr">Description</label>
              <textarea rows="4" class="main-input__field main-input__field--textarea"></textarea>
              <div class="main-input__message">
                <i class="main-input__message-icon icon icon-triangle-warning-sm"></i>
                <span class="main-input__message-txt">Error message</span>
              </div>
            </div>

            <div class="create-goal__input-short main-input">
              <label class="main-input__label" for="goal_priority">Priority</label>
              <select id="goal_priority" class="main-input__field main-input__field--xs">
                <option value="low">Low</option>
                <option value="medium">Medium</option>
                <option value="high">High</option>
              </select>
              <div class="main-input__message">
                <i class="main-input__message-icon icon icon-triangle-warning-sm"></i>
                <span class="main-input__message-txt">Error message</span>
              </div>
            </div>

            <div class="create-goal__input-short main-input">
              <label class="main-input__label" for="goal_date">Due Date</label>
              <input class="main-input__field main-input__field--xs" type="date" id="goal_date" />
              <div class="main-input__message">
                <i class="main-input__message-icon icon icon-triangle-warning-sm"></i>
                <span class="main-input__message-txt">Error message</span>
              </div>
            </div>

            <div class="create-goal__form-footer">
              <button type="button" class="main-btn main-btn--xs main-btn--grey mr-16">Cancel</button>
              <button type="submit" class="main-btn main-btn--xs">Create</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stubs/home/edit_gaol_page.html.erb
<!-- This page ha sthe same HTML as 'Create goal' page. The only difference is title name -->
<div class="goals-page">
  <div class="main-alert main-alert--error">
    <i class="main-alert__icon icon icon-triangle-warning"></i>
    <p class="main-alert__txt">Fill in due date.</p>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <h1 class="goals-page__title">Edit Goal</h1>

        <div class="create-goal__card main-card">
          <form>
            <div class="main-input">
              <label class="main-input__label" for="goal_title">Goal Title</label>
              <input class="main-input__field" type="text" id="goal_title" value="Learn RSpec" />
              <div class="main-input__message">
                <i class="main-input__message-icon icon icon-triangle-warning-sm"></i>
                <span class="main-input__message-txt">Error message</span>
              </div>
            </div>

            <div class="main-input">
              <label class="main-input__label" for="goal_descr">Description</label>
              <textarea rows="4" class="main-input__field main-input__field--textarea">Per mutat paulo mucius in. Aeterno democritum id sit, pro ut aliquip conceptam, cum alii nisl aliquid ex. Tritani corrumpit dignissim mei ex. An dicunt efficiantur intellegebat eos. Id est sumo habeo recteque, eum cu detraxit accusata, cu sea iusto interesset.</textarea>
              <div class="main-input__message">
                <i class="main-input__message-icon icon icon-triangle-warning-sm"></i>
                <span class="main-input__message-txt">Error message</span>
              </div>
            </div>

            <div class="create-goal__input-short main-input">
              <label class="main-input__label" for="goal_priority">Priority</label>
              <select id="goal_priority" class="main-input__field main-input__field--xs">
                <option value="low">Low</option>
                <option value="medium">Medium</option>
                <option value="high">High</option>
              </select>
              <div class="main-input__message">
                <i class="main-input__message-icon icon icon-triangle-warning-sm"></i>
                <span class="main-input__message-txt">Error message</span>
              </div>
            </div>

            <div class="create-goal__input-short main-input">
              <label class="main-input__label" for="goal_date">Due Date</label>
              <input class="main-input__field main-input__field--xs" type="date" id="goal_date" value="2019-09-01" />
              <div class="main-input__message">
                <i class="main-input__message-icon icon icon-triangle-warning-sm"></i>
                <span class="main-input__message-txt">Error message</span>
              </div>
            </div>

            <div class="create-goal__form-footer">
              <button type="button" class="main-btn main-btn--xs main-btn--grey mr-16">Cancel</button>
              <button type="submit" class="main-btn main-btn--xs">Create</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stubs/home/empty_gaols_page.html.erb
<div class="goals-page">
  <div class="goals-page__container container">
    <h1 class="goals-page__title">My Goals</h1>

    <div class="empty-goals__card main-card">
      <%=image_tag('working.svg', alt: 'Process', class: 'empty-goals__img')%>

      <p class="empty-goals__descr">You have no goals. Not going to lie, this is a bit sad.</p>

      <a href="/" class="main-btn">Create a Goal</a>
    </div>
  </div>
</div>

app/views/stubs/home/gaols_page_all_goals_tab.html.erb
<div class="goals-page">
  <div class="goals-page__container container">
    <!-- Update goal alert -->
    <div class="main-alert main-alert--success">
      <i class="main-alert__icon icon icon-circle-check-bold"></i>
      <p class="main-alert__txt">Your goal has been successfully updated.</p>
    </div>

    <!-- Delete goal alert -->
    <!-- <div class="main-alert main-alert--info">
      <i class="main-alert__icon icon icon-circle-check-bold"></i>
      <p class="main-alert__txt">Your goal has been successfully deleted.</p>
    </div> -->

    <div class="goals-page__header">
      <h1 class="goals-page__title">My Goals</h1>
      <a href="/" class="main-btn main-btn--xs mb-20 d-md-none">Create a Goal</a>
    </div>

    <div class="goals-page__nav main-card">
      <div class="main-tab">
        <a href="/" class="main-tab__item main-tab__item--active">All 8</a>
        <a href="/" class="main-tab__item">Incomplete  4</a>
        <a href="/" class="main-tab__item">Completed  4</a>
      </div>
      <div class="d-none d-md-block">
        <a href="/" class="main-btn main-btn--xs">Create a Goal</a>
      </div>
    </div>

    <div class="goals-page__card main-card">
      <div class="overflow-x-auto">
        <table class="goals-page__table main-table">
          <thead>
            <tr>
              <th>Goal Name</th>
              <th width="160">Due Date</th>
              <th width="160">Priority</th>
            </tr>
          </thead>
          <tbody>
          <!-- Hightlighted row -->
          <tr class="main-table__row--hightlight">
            <td>
              <div class="d-flex align-items-center">
                <i class="main-table__check icon icon-circle-check"></i>
                <p class="goals-page__table-txt mb-0">Learn RSpec</p>
              </div>
            </td>
            <td>12.08.2019</td>
            <td>
              <div class="d-flex align-items-center">
                <i class="in-low mr-4 icon icon-arrow-down"></i>
                Low
              </div>
            </td>
          </tr>
          <tr>
            <td>
              <div class="d-flex align-items-center">
                <i class="main-table__check icon icon-circle-check"></i>
                <p class="goals-page__table-txt mb-0">Metaprogramming</p>
              </div>
            </td>
            <td>16.08.2019</td>
            <td>
              <div class="d-flex align-items-center">
                <i class="in-high mr-4 icon icon-arrow-up"></i>
                High
              </div>
            </td>
          </tr>
          <!-- Checked row -->
          <tr class="main-table__row--checked">
            <td>
              <div class="d-flex align-items-center">
                <i class="main-table__check main-table__check--active icon icon-circle-check-filled"></i>
                <p class="goals-page__table-txt mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
              </div>
            </td>
            <td>12.08.2019</td>
            <td>
              <div class="d-flex align-items-center">
                <i class="in-medium mr-4 icon icon-arrow-up"></i>
                Medium
              </div>
            </td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/stubs/home/gaols_page_completed_goals_tab.html.erb
<div class="goals-page">
  <div class="goals-page__container container">

    <div class="goals-page__header">
      <h1 class="goals-page__title">My Goals</h1>
      <a href="/" class="main-btn main-btn--xs mb-20 d-md-none">Create a Goal</a>
    </div>

    <div class="goals-page__nav main-card">
      <div class="main-tab">
        <a href="/" class="main-tab__item">All 8</a>
        <a href="/" class="main-tab__item">Incomplete 4</a>
        <a href="/" class="main-tab__item main-tab__item--active">Completed 4</a>
      </div>
      <div class="d-none d-md-block">
        <a href="/" class="main-btn main-btn--xs">Create a Goal</a>
      </div>
    </div>

    <div class="goals-page__card main-card">
      <div class="overflow-x-auto">
        <table class="goals-page__table main-table">
          <thead>
            <tr>
              <th>Goal Name</th>
              <th width="160">Due Date</th>
              <th width="160">Priority</th>
            </tr>
          </thead>
          <tbody>
            <tr class="main-table__row--checked">
              <td>
                <div class="d-flex align-items-center">
                  <i class="main-table__check main-table__check--active icon icon-circle-check-filled"></i>
                  <p class="goals-page__table-txt mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                </div>
              </td>
              <td>12.08.2019</td>
              <td>
                <div class="d-flex align-items-center">
                  <i class="in-medium mr-4 icon icon-arrow-up"></i>
                  Medium
                </div>
              </td>
            </tr>
            <tr class="main-table__row--checked">
              <td>
                <div class="d-flex align-items-center">
                  <i class="main-table__check main-table__check--active icon icon-circle-check-filled"></i>
                  <p class="goals-page__table-txt mb-0">Learn Trailblazer</p>
                </div>
              </td>
              <td>12.08.2019</td>
              <td>
                <div class="d-flex align-items-center">
                  <i class="in-high mr-4 icon icon-arrow-up"></i>
                  High
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/stubs/index.html.erb
<div class="goals-page container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <h3>List of stubs</h3>

      <div class="main-card">
        <ul>
          <% @page_files.each do |key| %>
          <li>
            <%= link_to key, key %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>